name: Sync Calico version used for getting Tigera Operator manifest
on:
  schedule:
    # run on Monday at 7
    - cron:  '0 7 * * 1'
  workflow_dispatch:

jobs:
  sync-calico-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Update links to Tigera Operator manifest
        id: update-links
        run: .github/workflows/sync-calico-version.sh
      - name: Create pull request
        uses: peter-evans/create-pull-request@v4
        if: steps.update-links.outputs.UPDATE_NEEDED == 1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: calico-update-${{ steps.update-links.outputs.CALICO_VERSION }}
          title: Update calico to ${{ steps.update-links.outputs.CALICO_VERSION }}
          commit-message: Update calico to ${{ steps.update-links.outputs.CALICO_VERSION }}
          reviewers: flatcar/flatcar-maintainers
          delete-branch: true
